apiVersion: networking.gloo.solo.io/v2
kind: ExternalService
metadata:
  name: reviews-v5-external-service
  namespace: backend-apis-team
spec:
  hosts:
    - "reviews-external.bookinfo-backends.svc.cluster.local"
  ports:
    - name: https
      number: 9080
      protocol: HTTPS
      targetPort: 
        number: 443
      clientsideTls:
        sni: "reviews-v5.wooliesx.kasunt.fe.gl00.net"
  selector:
    external-endpoint: reviews-v5-external