apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: ext-auth-policy
  namespace: web-frontend-team
spec:
  applyToRoutes:
    - route:
        labels:
          enableExtAuth: "true"
  config:
    server:
      cluster: ${WEST_MESH_NAME}
      name: ext-auth-server
      namespace: ops-team
    glooAuth:
      configs:
        - oauth2:
            oidcAuthorizationCode:
              appUrl: "https://apps.${DOMAIN_NAME}"
              callbackPath: /callback
              clientId: "${CLIENT_ID}"
              clientSecretRef:
                name: keycloak-oidc
                namespace: web-frontend-team
              issuerUrl: "${KEYCLOAK_URL}/realms/master/"
              scopes:
                - email
              session:
                cookieOptions:
                  notSecure: true
              headers:
                idTokenHeader: jwt