kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oidc-ops-admin
subjects:
  - kind: User
    name: oidc:ops1@solo.io
roleRef:
  # Use the default cluster-admin cluster role to attach the user
  name: cluster-admin
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io