kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oidc-dev-backend
  namespace: backend-apis-team
subjects:
  - kind: User
    name: oidc:dev2@solo.io
roleRef:
  # Use the default view cluster role to attach the user
  name: view
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io