apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: global-cert-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    email: kasun.talwatta@solo.io
    privateKeySecretRef:
      name: global-cert-issuer
    solvers:
      - dns01:
          cloudDNS:
            # The ID of the GCP project
            project: $PROJECT_ID
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json